###

GET http://localhost:3000/usuarios

###

GET http://localhost:3000/personagem

###

POST http://localhost:3000/personagem
Content-Type: application/json

{
    "nome": "João do Star wars",
    "pilotagem": 3,
    "mira": 0,
    "carisma": 0
}

###